### ISSUE TITLE
App crashes when navigating between Information menu items

### ISSUE THREAD

**Issue by ssawchenko** [steamclock/internetmap#426]
Some issue with the tooltip library

1. Uninstall and reinstall to force first time experience 
2. With tooltip active, click info menu
3. Select Open Source
4. Close Open source page
5. Select Credits

App crashes (may take a few times repeating 3-5 to make crash occur)

07-07 12:53:10.840 19647-19647/com.peer1.internetmap E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.peer1.internetmap, PID: 19647
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.ViewGroup.getWidth()' on a null object reference
                                                                           at com.spyhunter99.supertooltips.ToolTipView.onPreDraw(ToolTipView.java:122)
                                                                           at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`
`

**Comment by ssawchenko** [comment]
Appears fixed by #411
