### ISSUE TITLE
Selecting "Your Location" on the Nexus 2013 does not work

### ISSUE THREAD

**Issue by ssawchenko** [steamclock/internetmap#475]
Despite having a network connection, selecting "your location" from the search list does not work. The message "Could not look up address' is seen.

**Comment by ssawchenko** [comment]
```
09-12 10:48:20.136 5714-14737/com.peer1.internetmap D/OkHttp: --> GET https://api.ipify.org/?format=json http/1.1
09-12 10:48:20.136 5714-14737/com.peer1.internetmap D/OkHttp: --> END GET
09-12 10:48:20.151 5714-5714/com.peer1.internetmap I/Choreographer: Skipped 284 frames!  The application may be doing too much work on its main thread.
09-12 10:48:20.660 5714-5714/com.peer1.internetmap E/CommonCallback: Call (https://api.ipify.org/?format=json) failed: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
09-12 10:48:20.774 5714-5714/com.peer1.internetmap E/CommonCallback: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:306)
                                                                         at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:195)
                                                                         at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148)
                                                                         at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
                                                                         at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
                                                                         at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
                                                                         at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
                                                                         at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
                                                                         at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
                                                                         at okhttp3.RealCall.getResponse(RealCall.java:240)
                                                                         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
                                                                         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                         at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                      Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                         at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
                                                                         at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
                                                                         at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:113)
                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:525)
                                                                         at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
                                                                         at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:195) 
                                                                         at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148) 
                                                                         at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111) 
                                                                         at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188) 
                                                                         at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127) 
                                                                         at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97) 
                                                                         at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289) 
                                                                         at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241) 
                                                                         at okhttp3.RealCall.getResponse(RealCall.java:240) 
                                                                         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198) 
                                                                         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203) 
                                                                         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187) 
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160) 
                                                                         at okhttp3.RealCall.access$100(RealCall.java:30) 
                                                                         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127) 
                                                                         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818) 
                                                                      Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
                                                                         at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318) 
                                                                         at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219) 
                                                                         at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:113) 
                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:525) 
                                                                         at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
                                                                         at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302) 
                                                                         at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:195) 
                                                                         at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148) 
                                                                         at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111) 
                                                                         at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188) 
                                                                         at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127) 
                                                                         at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97) 
                                                                         at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289) 
                                                                         at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241) 
                                                                         at okhttp3.RealCall.getResponse(RealCall.java:240) 
                                                                         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198) 
                                                                         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203) 
                                                                         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187) 
                                                                         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160) 
                                                                         at okhttp3.RealCall.access$100(RealCall.java:30) 
                                                                         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127) 
                                                                         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                         at java.lang.Thread.run(Thread.java:818)
```

**Comment by ssawchenko** [comment]
https://developer.android.com/training/articles/security-ssl.html
